language: python
python:
  - '2.7'
services:
  - mysql
env:
  - mysql_pass=''
addons:
  chrome: stable
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
  - mkdir bin
  - unzip chromedriver_linux64.zip -d bin
  - rm chromedriver_linux64.zip
  - export PATH=$PATH:$(pwd)/bin
install: 'make install'
before_script: 'make createproddb'
script: 'make all'
notifications:
  email: false
