# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 20:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import feature_phone.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pcari', '0052_auto_20170801_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording', models.FileField(upload_to=feature_phone.models.generate_recording_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording', models.FileField(upload_to=feature_phone.models.generate_recording_path)),
                ('tag', models.CharField(blank=True, default='', max_length=256)),
                ('language', models.CharField(blank=True, choices=[(b'en', 'English'), (b'tl', 'Filipino')], default='', max_length=8, validators=[django.core.validators.RegexValidator('^(|en|tl)$')])),
            ],
            options={
                'verbose_name_plural': 'instructions',
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('recording', models.FileField(upload_to=feature_phone.models.generate_recording_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FileField(upload_to=feature_phone.models.generate_recording_path)),
                ('gender', models.FileField(upload_to=feature_phone.models.generate_recording_path)),
                ('location', models.FileField(upload_to=feature_phone.models.generate_recording_path)),
                ('language', models.CharField(blank=True, choices=[(b'en', 'English'), (b'tl', 'Filipino')], default='', max_length=8, validators=[django.core.validators.RegexValidator('^(|en|tl)$')])),
                ('related_object', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_object', to='pcari.Respondent')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('instructions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feature_phone.Instructions')),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
            bases=('feature_phone.instructions', models.Model),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_phone.Respondent'),
        ),
        migrations.AddField(
            model_name='commentrating',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_phone.QuestionResponse'),
        ),
        migrations.AddField(
            model_name='commentrating',
            name='related_object',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_object', to='pcari.CommentRating'),
        ),
        migrations.AddField(
            model_name='commentrating',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_phone.Respondent'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_phone.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='commentrating',
            unique_together=set([('comment', 'respondent')]),
        ),
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together=set([('question', 'respondent'), ('content_type', 'object_id')]),
        ),
    ]
