# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_phone', '0003_auto_20171027_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
