# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_phone', '0005_response_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='age_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='respondent',
            name='gender_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='respondent',
            name='location_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
