# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_phone', '0006_auto_20171103_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='age_url',
            field=models.URLField(blank=True, default='', verbose_name='Age Recording URL'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='gender_url',
            field=models.URLField(blank=True, default='', verbose_name='Gender Recording URL'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='location_url',
            field=models.URLField(blank=True, default='', verbose_name='Location Recording URL'),
        ),
        migrations.AlterField(
            model_name='response',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='URL'),
        ),
    ]
