# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_phone', '0008_auto_20180115_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='call_sid',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
