# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_phone', '0010_auto_20180118_1104'),
        ('feature_phone', '0010_auto_20180117_1121'),
    ]

    operations = [
    ]
