# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-02 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_phone', '0011_merge_20180125_0719'),
        ('feature_phone', '0011_auto_20180129_0122'),
    ]

    operations = [
    ]
