# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_phone', '0012_auto_20180301_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructions',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name_plural': 'instructions'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
