# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_phone', '0004_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
