# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_phone', '0007_auto_20171103_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='age_url',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='gender_url',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='location_url',
        ),
        migrations.AlterField(
            model_name='instructions',
            name='key',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='instructions',
            unique_together=set([('key', 'language')]),
        ),
    ]
