# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0005_auto_20160727_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='alt_question',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=500),
        ),
    ]
