# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0007_generalsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='alt_question',
            new_name='tagalog_question',
        ),
    ]
