# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0010_auto_20160804_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_begin_button',
            field=models.CharField(default='Magsimula', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_next_button',
            field=models.CharField(default='Susunod', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_post_button',
            field=models.CharField(default='Koreo', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_skip_button',
            field=models.CharField(default='Laktawan', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_submit_button',
            field=models.CharField(default='Ipasa', max_length=20),
        ),
    ]
