# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0011_auto_20160804_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSetting',
            new_name='GeneralSettings',
        ),
    ]
