# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0016_auto_20160808_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='response',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
