# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0017_rating_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='english_bloom_description',
            field=models.CharField(default='Each sphere below represents an idea proposed by another user', max_length=500),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='tagalog_bloom_description',
            field=models.CharField(default='Tagalog Bloom Description', max_length=500),
        ),
    ]
