# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0036_auto_20161003_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='original_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Tagalog', 'Tagalog')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tagalog_comment',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
