# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0042_auto_20161129_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='english_graph_description',
            field=models.CharField(default='The plots below show the average trend of the ratings.', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='english_landing_description',
            field=models.CharField(default='How prepared are you in times of disaster? %d barangay citizens have responded. Join them! It only takes a minute.', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='english_rate_more_ideas',
            field=models.CharField(default='Rate More Ideas', max_length=50),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='english_share_description',
            field=models.CharField(default='Thank you for participating. Please share Malasakit with your friends and family', max_length=300),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='english_suggest_own',
            field=models.CharField(default='Suggest Your Own Idea', max_length=50),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='filipino_age',
            field=models.CharField(default='Edad', max_length=30),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='filipino_error',
            field=models.CharField(default='Paki sagutan ang mga sumusunod para maikumpara ang iyong sagot sa iba', max_length=300),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='filipino_gender',
            field=models.CharField(default='Kasarian', max_length=30),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='filipino_graph_description',
            field=models.CharField(default='Sa papaanong pamamaraan makakatulong ang inyong barangay upang higit na maging handa ka para sa isang kalamidad', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='filipino_rate_more_ideas',
            field=models.CharField(default='Bigyan ng grado ang iba pang ideya', max_length=50),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='filipino_select',
            field=models.CharField(default='Pili ng kasarian', max_length=30),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='filipino_share_description',
            field=models.CharField(default='Maraming salamat. Paki bahagi ang Malasakit sa inyong mga kaibigan at pamilya', max_length=300),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='filipino_suggest_own',
            field=models.CharField(default='Magmungkahi ng iyong sariling ideya', max_length=50),
        ),
    ]
