# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0044_auto_20161205_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='english_personal',
            field=models.CharField(default='Please enter the following to see how you compare with others', max_length=300),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='filipino_personal',
            field=models.CharField(default='Paki sagutan ang mga sumusunod para maikumpara ang iyong sagot sa iba', max_length=300),
        ),
    ]
