# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 09:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0049_auto_20170701_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', 'English'), (b'tl', 'Filipino')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='comment',
            name='predecessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='pcari.Comment'),
        ),
        migrations.AlterField(
            model_name='commentrating',
            name='predecessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='pcari.CommentRating'),
        ),
        migrations.AlterField(
            model_name='optionquestion',
            name='predecessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='pcari.OptionQuestion'),
        ),
        migrations.AlterField(
            model_name='optionquestionchoice',
            name='predecessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='pcari.OptionQuestionChoice'),
        ),
        migrations.AlterField(
            model_name='qualitativequestion',
            name='predecessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='pcari.QualitativeQuestion'),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='predecessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='pcari.QuantitativeQuestion'),
        ),
        migrations.AlterField(
            model_name='quantitativequestionrating',
            name='predecessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='pcari.QuantitativeQuestionRating'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', 'English'), (b'tl', 'Filipino')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='predecessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='pcari.Respondent'),
        ),
    ]
