# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 19:30
from __future__ import unicode_literals

from django.db import migrations, models


def make_update_sentinels_forward(rating_model_name):
    def update_sentinels_forward(apps, schema_editor):
        RatingModel = apps.get_model('pcari', rating_model_name)
        db_alias = schema_editor.connection.alias

        RatingModel.objects.filter(score=-2).delete()
        RatingModel.objects.filter(score=-1).update(score=None)
    return update_sentinels_forward


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0052_auto_20170801_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='score',
            field=models.SmallIntegerField(default=None, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='quantitativequestionrating',
            name='score',
            field=models.SmallIntegerField(default=None, null=True, blank=True),
        ),
        migrations.RunPython(make_update_sentinels_forward('CommentRating')),
        migrations.RunPython(make_update_sentinels_forward('QuantitativeQuestionRating')),
        migrations.AlterField(
            model_name='commentrating',
            name='score',
            field=models.PositiveSmallIntegerField(default=None, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='quantitativequestionrating',
            name='score',
            field=models.PositiveSmallIntegerField(default=None, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=9, null=True),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='min_score',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
