# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0055_respondent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quantitativequestionrating',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
