# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0054_auto_20170809_1839'),
        ('pcari', '0055_respondent_uuid'),
    ]

    operations = [
    ]
