# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0057_auto_20170904_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='show_statistics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quantitativequestion',
            name='show_statistics',
            field=models.BooleanField(default=True),
        ),
    ]
