# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0058_auto_20170911_2338'),
        ('pcari', '0056_merge_20170823_1722'),
    ]

    operations = [
    ]
