# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 09:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0059_remove_comment_show_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', 'English'), (b'tl', 'Filipino'), (b'es', 'Spanish'), (b'ceb', 'Cebuano'), (b'ilo', 'Ilocano')], default='', max_length=8, validators=[django.core.validators.RegexValidator('^(|en|tl|es|ceb|ilo)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', 'English'), (b'tl', 'Filipino'), (b'es', 'Spanish'), (b'ceb', 'Cebuano'), (b'ilo', 'Ilocano')], default='', max_length=8, validators=[django.core.validators.RegexValidator('^(|en|tl|es|ceb|ilo)$')]),
        ),
    ]
