# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0061_auto_20171027_0812'),
        ('pcari', '0060_auto_20171130_0904'),
    ]

    operations = [
    ]
