# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 11:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0062_merge_20180116_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=64)),
                ('municipality', models.CharField(max_length=64)),
                ('division', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', 'English'), (b'tl', 'Filipino'), (b'ceb', 'Cebuano'), (b'ilo', 'Ilocano')], default='', max_length=8, validators=[django.core.validators.RegexValidator('^(|en|tl|ceb|ilo)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', 'English'), (b'tl', 'Filipino'), (b'ceb', 'Cebuano'), (b'ilo', 'Ilocano')], default='', max_length=8, validators=[django.core.validators.RegexValidator('^(|en|tl|ceb|ilo)$')]),
        ),
    ]
