# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0066_auto_20180201_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Indicates whether data collection is occuring at this location, and should be presented to participants as an answer to residence questions.', verbose_name='Enabled as input'),
        ),
    ]
