# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0067_auto_20180129_0122'),
        ('pcari', '0067_auto_20180201_2010'),
    ]

    operations = [
    ]
