# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0004_auto_20160721_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progression',
            old_name='evaluation',
            new_name='bloom',
        ),
        migrations.AddField(
            model_name='progression',
            name='num_peer_rated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progression',
            name='peer_rating',
            field=models.BooleanField(default=False),
        ),
    ]
