# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0006_auto_20160804_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_language', models.CharField(choices=[('ENG', 'English'), ('TAG', 'Tagalog')], default='ENG', max_length=3)),
            ],
        ),
    ]
