# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0008_auto_20160804_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='main_comment_description',
            field=models.CharField(default='Please write your comment below', max_length=500),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='main_feedback_description',
            field=models.CharField(default="At the end you'll have a chance to give us more feedback", max_length=500),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='main_graph_description',
            field=models.CharField(default='The plots below show the average trend of the ratings.', max_length=500),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='main_landing_description',
            field=models.CharField(default="Join others to amplify Philippine's collective intelligence", max_length=500),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='main_peer_evaluation_description',
            field=models.CharField(default='How important is this issue?', max_length=500),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='main_question_description',
            field=models.CharField(default="Please grade Philippine government's effectiveness on:", max_length=500),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_begin_button',
            field=models.CharField(default='Begin', max_length=10),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_comment_description',
            field=models.CharField(default='Please write your comment below', max_length=500),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_feedback_description',
            field=models.CharField(default="At the end you'll have a chance to give us more feedback", max_length=500),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_graph_description',
            field=models.CharField(default='The plots below show the average trend of the ratings.', max_length=500),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_landing_description',
            field=models.CharField(default="Join others to amplify Philippine's collective intelligence", max_length=500),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_next_button',
            field=models.CharField(default='Next', max_length=10),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_peer_evaluation_description',
            field=models.CharField(default='How important is this issue?', max_length=500),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_post_button',
            field=models.CharField(default='Post', max_length=10),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_question_description',
            field=models.CharField(default="Please grade Philippine government's effectiveness on:", max_length=500),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_skip_button',
            field=models.CharField(default='Skip', max_length=10),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_submit_button',
            field=models.CharField(default='Submit', max_length=10),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='main_language',
            field=models.CharField(choices=[('English', 'English'), ('Tagalog', 'Tagalog')], default='English', max_length=15),
        ),
    ]
