# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0009_auto_20160804_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsetting',
            old_name='main_language',
            new_name='default_language',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='main_comment_description',
            new_name='english_comment_description',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='main_feedback_description',
            new_name='english_feedback_description',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='main_graph_description',
            new_name='english_graph_description',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='main_landing_description',
            new_name='english_landing_description',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='main_peer_evaluation_description',
            new_name='english_peer_evaluation_description',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='main_question_description',
            new_name='english_question_description',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='secondary_begin_button',
            new_name='tagalog_begin_button',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='secondary_comment_description',
            new_name='tagalog_comment_description',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='secondary_feedback_description',
            new_name='tagalog_feedback_description',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='secondary_graph_description',
            new_name='tagalog_graph_description',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='secondary_landing_description',
            new_name='tagalog_landing_description',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='secondary_next_button',
            new_name='tagalog_next_button',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='secondary_peer_evaluation_description',
            new_name='tagalog_peer_evaluation_description',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='secondary_post_button',
            new_name='tagalog_post_button',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='secondary_question_description',
            new_name='tagalog_question_description',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='secondary_skip_button',
            new_name='tagalog_skip_button',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='secondary_submit_button',
            new_name='tagalog_submit_button',
        ),
    ]
