# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0012_auto_20160804_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='tagalog_comment_description',
            field=models.CharField(default='Tagalog Comment Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='tagalog_feedback_description',
            field=models.CharField(default='Tagalog Feedback Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='tagalog_graph_description',
            field=models.CharField(default='Tagalog Graph Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='tagalog_landing_description',
            field=models.CharField(default='Tagalog Landing', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='tagalog_peer_evaluation_description',
            field=models.CharField(default='Tagalog Peer Evaluation', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='tagalog_question_description',
            field=models.CharField(default='Tagalog Question', max_length=500),
        ),
    ]
