# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0014_auto_20160808_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualitative_Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=500)),
                ('tagalog_question', models.CharField(default='walang tagalog pagsasalin', max_length=500)),
            ],
        ),
    ]
