# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0015_qualitative_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qualitative_Question',
            new_name='QualitativeQuestion',
        ),
        migrations.RenameModel(
            old_name='Quantitative_Question',
            new_name='QuantitativeQuestion',
        ),
    ]
