# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0019_auto_20160809_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tagalog_comment',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
