# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0021_auto_20160825_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitativequestion',
            name='average_score',
            field=models.IntegerField(default=0),
        ),
    ]
