# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0023_auto_20160826_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progression',
            new_name='UserProgression',
        ),
    ]
