# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0025_auto_20160829_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitativequestion',
            name='tag',
            field=models.CharField(default='', max_length=50),
        ),
    ]
