# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 03:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pcari', '0026_quantitativequestion_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=1000, null=True)),
                ('tagalog_comment', models.CharField(default='', max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('average_score', models.IntegerField(default=0)),
                ('number_rated', models.IntegerField(default=0)),
                ('tag', models.CharField(default='', max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='english_comment_description',
            field=models.CharField(default='How could your Barangay help you better prepare for a disaster?', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='english_graph_description',
            field=models.CharField(default="Here's how you compare with others", max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='english_landing_description',
            field=models.CharField(default='Take a minute to see how prepared you are and join the %d others who have visited so far in an online discussion about preparedness.', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='english_peer_evaluation_description',
            field=models.CharField(default='How helpful is this suggestion? ', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='english_question_description',
            field=models.CharField(default='Please select how strongly you agree with the following statement', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_begin_button',
            field=models.CharField(default='Simulan', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_bloom_description',
            field=models.CharField(default='Kumakatawan sa mungkahing ideya ng ibang tao ang bawat bilog sa ibaba', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_comment_description',
            field=models.CharField(default='Sa papaanong pamamaraan makakatulong ang inyong barangay upang higit na maging handa ka para sa isang kalamidad', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_feedback_description',
            field=models.CharField(default='Sa dulo, mabibigyan ka ng pagkakataon na magbigay ng iyong mungkahing ideya', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_graph_description',
            field=models.CharField(default='no translation provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_landing_description',
            field=models.CharField(default='Maglaan ng isang minuto para tingnan kung gaano kayo kahanda, at sumali sa %d iba pa na bumisita sa isang onlayn na diskusyon tungkol sa kahandaan.', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_peer_evaluation_description',
            field=models.CharField(default='Gaano ka halaga ang mungkahing ito?', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_post_button',
            field=models.CharField(default='Ipasa', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_question_description',
            field=models.CharField(default='Paki pili kung gaano kayo sumasang-ayon sa mga sumusunod na pangungusap', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='tagalog_submit_button',
            field=models.CharField(default='Isumite', max_length=20),
        ),
    ]
