# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0027_auto_20160831_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitativequestion',
            name='number_rated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='average_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='flaggedcomment',
            name='average_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='flaggedcomment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='progression',
            name='bloom',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='progression',
            name='comment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='progression',
            name='landing',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='progression',
            name='logout',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='progression',
            name='peer_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='progression',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='progression',
            name='review',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='average_score',
            field=models.FloatField(default=0),
        ),
    ]
