# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0031_auto_20160831_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitativequestion',
            name='tagalog_tag',
            field=models.CharField(default='', max_length=50),
        ),
    ]
