# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0035_auto_20160907_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogression',
            name='personal_data',
            field=models.NullBooleanField(default=False),
        ),
    ]
