# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0037_auto_20161005_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='accounted',
        ),
        migrations.AddField(
            model_name='commentrating',
            name='accounted',
            field=models.BooleanField(default=False),
        ),
    ]
