# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0038_auto_20161005_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='english_about_pcari',
            field=models.CharField(default='About PCARI', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_age',
            field=models.CharField(default='Age', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_error',
            field=models.CharField(default='Please enter the following fields', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_exit',
            field=models.CharField(default='Exit', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_female',
            field=models.CharField(default='Female', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_gender',
            field=models.CharField(default='Gender', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_learn_more',
            field=models.CharField(default='Learn more about how to be prepared for a disaster', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_male',
            field=models.CharField(default='Male', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_more_info',
            field=models.CharField(default='More Information', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_question_of',
            field=models.CharField(default='Question %d of %d', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_rate_more_ideas',
            field=models.CharField(default='Rate More Ideas', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_scale_description',
            field=models.CharField(default='0 (strongly disagree) to 9 (strongly agree)', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_select',
            field=models.CharField(default='Select', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_share_description',
            field=models.CharField(default='Please share Malasakit with your friends and family', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_short_description',
            field=models.CharField(default='A project by the CITRIS Connected Communities Initiative at UC Berkeley and the Philippine Commission on Higher Education through the Philippine-California Advanced Research Institutes Project.', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='english_suggest_own',
            field=models.CharField(default='Suggest Your Own Idea', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_about_pcari',
            field=models.CharField(default='Tungkol sa PCARI', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_age',
            field=models.CharField(default='Susunod', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_error',
            field=models.CharField(default='(TAGALOG) Please enter the following fields', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_exit',
            field=models.CharField(default='Lumabas', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_female',
            field=models.CharField(default='Babae', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_gender',
            field=models.CharField(default='Edad', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_learn_more',
            field=models.CharField(default='Alamin ang iba pang impormasyon kung paano magiging handa sa isang sakuna', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_male',
            field=models.CharField(default='Lalaki', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_more_info',
            field=models.CharField(default='Iba pang impormasyon', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_question_of',
            field=models.CharField(default='Ika-%d ng %d katanungan', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_rate_more_ideas',
            field=models.CharField(default='Bigyan ng grado ang iba pang ideya', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_scale_description',
            field=models.CharField(default='Mula 0 (hinding-hindi ako sumasang-ayon) hanggang 9 (lubos akong sumasang-ayon)', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_select',
            field=models.CharField(default='Pili ang', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_share_description',
            field=models.CharField(default='Paki bahagi ang Malasakit sa inyong mga kaibigan at pamilya', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_short_description',
            field=models.CharField(default='Isang proyekto ng CITRIS Connected Communities Initiative ng UC Berkeley, at ng Commission on Higher Education ng Pilipinas sa pamamagitan ng Philippine-California Advanced Research Institutes Project', max_length=255),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tagalog_suggest_own',
            field=models.CharField(default='Magmungkahi ng iyong sariling ideya', max_length=255),
        ),
    ]
