# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0041_auto_20161129_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='barangay',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
