# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0043_auto_20161129_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='filipino_bloom_description',
            field=models.CharField(default='Kumakatawan sa mungkahing ideya ng ibang tao ang bawat bilog sa ibaba. Pindutin ang isang bilog sa ibaba para magsimula.', max_length=500),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='filipino_graph_description',
            field=models.CharField(default='Ang talaguhitan sa ibaba ay nagpapakita ng madalas na sagot ng ibang tao.', max_length=500),
        ),
    ]
