# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0045_auto_20161205_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Filipino', 'Filipino')], default='Filipino', max_length=15),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='filipino_landing_description',
            field=models.CharField(default='Gaano ka kahanda sa panahon ng kalamidad? %d na ang nag MALASAKIT. Sali na! Isang minuto lamang ang kailangan.', max_length=500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
