# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 22:03
from __future__ import unicode_literals

from django.db import models
from django.db import migrations


def populate_questions_forward(apps, schema_editor):
    QuantitativeQuestion = apps.get_model('pcari', 'QuantitativeQuestion')
    QualitativeQuestion = apps.get_model('pcari', 'QualitativeQuestion')
    Question = apps.get_model('pcari', 'Question')
    db_alias = schema_editor.connection.alias

    Question.objects.using(db_alias).bulk_create([
        Question(prompt=question.question, tag=question.tag)
        for question in QuantitativeQuestion.objects.all()
    ])
    Question.objects.using(db_alias).bulk_create([
        Question(prompt=question.question)
        for question in QualitativeQuestion.objects.all()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0048_auto_20170407_1732'),
    ]

    operations = [
        migrations.DeleteModel('GeneralSetting'),
        migrations.DeleteModel('Progression'),
        migrations.DeleteModel('FlaggedComment'),
        migrations.CreateModel('Question', [
            ('prompt', models.TextField(blank=True)),
            ('tag', models.CharField(max_length=64, blank=True, default=''))
        ]),
        migrations.RunPython(populate_questions_forward),
        migrations.DeleteModel('QuantitativeQuestion'),
        migrations.DeleteModel('QualitativeQuestion'),
    ]
