# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0049_model_refactor'),
    ]

    operations = [
        migrations.AddField('QuantitativeQuestion', 'left_end', models.TextField(blank=True)),
        migrations.AddField('QuantitativeQuestion', 'right_end', models.TextField(blank=True)),
    ]
