# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 05:27
from __future__ import unicode_literals

from django.db import migrations, models


INPUT_TYPES = [
    ('select', 'select'),
    ('range', 'range'),
    ('number', 'number'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0049_model_refactor'),
    ]

    operations = [
        migrations.AddField('QuantitativeQuestion', 'left_text', models.TextField(blank=True, default='')),
        migrations.AddField('QuantitativeQuestion', 'right_text', models.TextField(blank=True, default='')),
        migrations.AddField('QuantitativeQuestion', 'input_type', models.CharField(max_length=64, choices=INPUT_TYPES, default='range')),
    ]
