# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0050_auto_20170605_1935'),
    ]

    operations = [
        migrations.RenameField('QuantitativeQuestion', 'left_end', 'left_text'),
        migrations.RenameField('QuantitativeQuestion', 'right_end', 'right_text'),
    ]
