# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


def change_language_code_forward(apps, schema_editor):
    Comment = apps.get_model('pcari', 'Comment')
    Respondent = apps.get_model('pcari', 'Respondent')
    db_alias = schema_editor.connection.alias

    for comment in Comment.objects.using(db_alias).all():
        if comment.language == 'ENG':
            comment.language = 'en'
        elif comment.language == 'FIL':
            comment.language = 'tl'
        comment.save()

    for respondent in Respondent.objects.using(db_alias).all():
        if respondent.language == 'ENG':
            respondent.language = 'en'
        elif respondent.language == 'FIL':
            respondent.language = 'tl'
        respondent.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0051_auto_20170605_2001'),
    ]

    operations = [
        migrations.AlterField('Comment', 'language',
                              models.CharField(max_length=2, choices=settings.LANGUAGES)),
        migrations.AlterField('Respondent', 'language',
                              models.CharField(max_length=2, choices=settings.LANGUAGES)),
        migrations.RunPython(change_language_code_forward),
    ]
