# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0051_auto_20170705_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('M', 'Male'), ('F', 'Female')], default='', max_length=1, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
    ]
