# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0051_auto_20170605_2001'),
        ('pcari', '0050_auto_20170605_1935'),
    ]

    operations = [
    ]
