# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 20:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0052_auto_20170801_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', 'English')], default='', max_length=8, validators=[django.core.validators.RegexValidator('^(|en)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', 'English')], default='', max_length=8, validators=[django.core.validators.RegexValidator('^(|en)$')]),
        ),
    ]
