# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0053_auto_20170804_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionquestion',
            name='_options_text',
            field=models.TextField(blank=True, default=b'[]', help_text='A JSON list has the form: <tt>["Choice A", "Choice B"]</tt>. Each option is wrapped in double quotation marks. The options are then separated by commas within the square brackets.', verbose_name='Options as JSON'),
        ),
    ]
