# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0053_auto_20170804_1930'),
        ('pcari', '0053_auto_20170807_2033'),
    ]

    operations = [
    ]
