# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0053_comment_nullable'),
    ]

    operations = [
        migrations.AlterField('Respondent', 'location', models.CharField(max_length=512, default=None, blank=True, null=True))
    ]

