# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


INPUT_TYPES = (
    ('range', 'range'),
    ('number', 'number')
)

class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0055_empty_strings_to_null'),
    ]

    operations = [
        migrations.AddField('QuantitativeQuestion', 'min_score',
                            models.PositiveSmallIntegerField(default=0,
                                                             null=True,
                                                             blank=True)),
        migrations.AddField('QuantitativeQuestion', 'max_score',
                            models.PositiveSmallIntegerField(default=9,
                                                             null=True,
                                                             blank=True)),
        migrations.AddField('QuantitativeQuestion', 'input_type',
                            models.CharField(max_length=16, choices=INPUT_TYPES,
                                             default='range', blank=True)),
    ]
