# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0056_auto_20170823_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionquestion',
            name='order',
            field=models.IntegerField(blank=True, default=None, help_text='Questions are displayed using this value sorted in ascending order. Questions without a given <tt>order</tt> are displayed last.', null=True),
        ),
        migrations.AddField(
            model_name='qualitativequestion',
            name='order',
            field=models.IntegerField(blank=True, default=None, help_text='Questions are displayed using this value sorted in ascending order. Questions without a given <tt>order</tt> are displayed last.', null=True),
        ),
        migrations.AddField(
            model_name='quantitativequestion',
            name='order',
            field=models.IntegerField(blank=True, default=None, help_text='Questions are displayed using this value sorted in ascending order. Questions without a given <tt>order</tt> are displayed last.', null=True),
        ),
    ]
