# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0056_questions_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, default='', max_length=256)),
                ('options_as_json', models.TextField(blank=True)),
                ('input_type', models.CharField(blank=True, choices=[('select', 'select'), ('radio', 'radio')], default='select', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('option', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcari.OptionQuestion')),
            ],
        ),
        migrations.AlterField(
            model_name='quantitativequestionrating',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualitativequestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qualitativequestion',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='language',
            field=models.CharField(choices=[(b'en', 'English'), (b'tl', 'Filipino')], max_length=2),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='location',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quantitativequestionrating',
            unique_together=set([('respondent', 'question')]),
        ),
        migrations.AddField(
            model_name='optionresponse',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcari.Respondent'),
        ),
        migrations.AlterUniqueTogether(
            name='optionresponse',
            unique_together=set([('respondent', 'question')]),
        ),
    ]
