# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0056_merge_20170822_1919'),
        ('pcari', '0057_auto_20170904_2021'),
    ]

    operations = [
    ]
