# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0057_auto_20170615_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionquestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='optionquestion',
            name='predecessor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcari.OptionQuestion'),
        ),
        migrations.AddField(
            model_name='optionresponse',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='optionresponse',
            name='predecessor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcari.OptionResponse'),
        ),
        migrations.AlterField(
            model_name='commentrating',
            name='score_history_text',
            field=models.CharField(default=b'-2', max_length=256),
        ),
        migrations.AlterField(
            model_name='quantitativequestionrating',
            name='score_history_text',
            field=models.CharField(default=b'-2', max_length=256),
        ),
    ]
