# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0058_auto_20170911_2338'),
        ('pcari', '0058_merge_20170910_1909'),
    ]

    operations = [
    ]
