# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 21:26
from __future__ import unicode_literals

from django.db import migrations, models


def populate_score_forward(apps, schema_editor):
    QuantitativeQuestionRating = apps.get_model('pcari', 'QuantitativeQuestionRating')
    CommentRating = apps.get_model('pcari', 'CommentRating')
    db_alias = schema_editor.connection.alias

    for rating in QuantitativeQuestionRating.objects.using(db_alias).all():
        rating.score = int(rating.score_history_text.split(',')[-1])
        rating.save()

    for rating in CommentRating.objects.using(db_alias).all():
        rating.score = int(rating.score_history_text.split(',')[-1])
        rating.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0058_auto_20170623_0521'),
    ]

    operations = [
        migrations.AddField('QuantitativeQuestionRating', 'score', models.SmallIntegerField(default=-2)),
        migrations.AddField('CommentRating', 'score', models.SmallIntegerField(default=-2)),
        migrations.RunPython(populate_score_forward),
        migrations.RemoveField('QuantitativeQuestionRating', 'score_history_text'),
        migrations.RemoveField('CommentRating', 'score_history_text'),
    ]
