# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0059_remove_comment_show_statistics'),
        ('pcari', '0059_merge_20171013_0238'),
    ]

    operations = [
    ]
