# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def port_locations_forward(apps, schema_editor):
    Respondent = apps.get_model('pcari', 'Respondent')
    Location = apps.get_model('pcari', 'Location')
    db_alias = schema_editor.connection.alias
    for respondent in Respondent.objects.all():
        division = respondent._location
        respondent.location, _ = Location.objects.get_or_create(
            division=division.strip(),
        )
        respondent.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0063_auto_20180117_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=64, default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='division',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='municipality',
            field=models.CharField(blank=True, max_length=64, default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.CharField(blank=True, max_length=64, default=''),
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='location',
            new_name='_location',
        ),
        migrations.AddField(
            model_name='respondent',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='pcari.Location'),
            preserve_default=True,
        ),
        migrations.RunPython(port_locations_forward),
        migrations.RemoveField(
            model_name='respondent',
            name='_location',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('country', 'province', 'municipality', 'division')]),
        ),
    ]
