# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0064_auto_20180117_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='division',
            field=models.CharField(help_text='A basic administrative unit within a municipality.', max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Indicates whether data collection is occuringat this location, and should be presented to participants as an answer to residence questions.'),
        ),
    ]
