# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0065_auto_20180119_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='commentrating',
            name='active',
        ),
        migrations.RemoveField(
            model_name='commentrating',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='optionquestion',
            name='active',
        ),
        migrations.RemoveField(
            model_name='optionquestion',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='optionquestionchoice',
            name='active',
        ),
        migrations.RemoveField(
            model_name='optionquestionchoice',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='qualitativequestion',
            name='active',
        ),
        migrations.RemoveField(
            model_name='qualitativequestion',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='quantitativequestion',
            name='active',
        ),
        migrations.RemoveField(
            model_name='quantitativequestion',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='quantitativequestion',
            name='show_statistics',
        ),
        migrations.RemoveField(
            model_name='quantitativequestionrating',
            name='active',
        ),
        migrations.RemoveField(
            model_name='quantitativequestionrating',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='active',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='completed_survey',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='submitted_personal_data',
        ),
        migrations.AddField(
            model_name='comment',
            name='original',
            field=models.ForeignKey(default=None, help_text='If this comment is a translation, this field references the original suggestion.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pcari.Comment'),
        ),
        migrations.AddField(
            model_name='optionquestion',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Indicates whether this question should be asked to users.'),
        ),
        migrations.AddField(
            model_name='qualitativequestion',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Indicates whether this question should be asked to users.'),
        ),
        migrations.AddField(
            model_name='quantitativequestion',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Indicates whether this question should be asked to users.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Indicates whether this comment should be reviewed for a lack of constructive content. Flagged comments will not be displayed to participants.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='One or more comma-separated topics this comment relates to.', max_length=256),
        ),
        migrations.AlterField(
            model_name='optionquestion',
            name='_options_text',
            field=models.TextField(blank=True, default=b'[]', help_text='The list should be formatted as follows: <tt>["Choice A", "Choice B"]</tt>. Each option is wrapped in double quotation marks. The options are then separated by commas within the square brackets.', verbose_name='List of options'),
        ),
        migrations.AlterField(
            model_name='optionquestion',
            name='input_type',
            field=models.CharField(choices=[('select', 'Dropdown'), ('radio', 'Multiple choice')], default='select', help_text='What user interface element should be used.', max_length=16),
        ),
        migrations.AlterField(
            model_name='optionquestion',
            name='order',
            field=models.IntegerField(blank=True, default=None, help_text='This field determines how questions are ordered. Questions with greater <tt>order</tt> values are displayed later. Questions without an <tt>order</tt> are displayed last.', null=True),
        ),
        migrations.AlterField(
            model_name='optionquestion',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='One or more comma-separated topics this question relates to.', max_length=256),
        ),
        migrations.AlterField(
            model_name='qualitativequestion',
            name='order',
            field=models.IntegerField(blank=True, default=None, help_text='This field determines how questions are ordered. Questions with greater <tt>order</tt> values are displayed later. Questions without an <tt>order</tt> are displayed last.', null=True),
        ),
        migrations.AlterField(
            model_name='qualitativequestion',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='One or more comma-separated topics this question relates to.', max_length=256),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='input_type',
            field=models.CharField(choices=[('range', 'Slider'), ('number', 'Numeric text')], default='range', help_text='What user interface element should be used.', max_length=16),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='left_anchor',
            field=models.TextField(blank=True, default='', help_text='This label describes what the lowest score means.'),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=6, null=True, verbose_name='Minimum score'),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='min_score',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Maximum score'),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='order',
            field=models.IntegerField(blank=True, default=None, help_text='This field determines how questions are ordered. Questions with greater <tt>order</tt> values are displayed later. Questions without an <tt>order</tt> are displayed last.', null=True),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='right_anchor',
            field=models.TextField(blank=True, default='', help_text='This label describes what the greatest score means.'),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='One or more comma-separated topics this question relates to.', max_length=256),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='uuid',
            field=models.UUIDField(blank=True, default=None, editable=False, help_text='Unique identifier generated client-side.', null=True, unique=True),
        ),
    ]
