# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0065_auto_20180119_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='commentrating',
            name='active',
        ),
        migrations.RemoveField(
            model_name='commentrating',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='optionquestion',
            name='active',
        ),
        migrations.RemoveField(
            model_name='optionquestion',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='optionquestionchoice',
            name='active',
        ),
        migrations.RemoveField(
            model_name='optionquestionchoice',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='qualitativequestion',
            name='active',
        ),
        migrations.RemoveField(
            model_name='qualitativequestion',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='quantitativequestion',
            name='active',
        ),
        migrations.RemoveField(
            model_name='quantitativequestion',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='quantitativequestionrating',
            name='active',
        ),
        migrations.RemoveField(
            model_name='quantitativequestionrating',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='active',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='predecessor',
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=6, null=True, verbose_name='Minimum score'),
        ),
        migrations.AlterField(
            model_name='quantitativequestion',
            name='min_score',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Maximum score'),
        ),
    ]
