# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-29 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0065_auto_20180119_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Indicates whether data collection is occuring at this location, and should be presented to participants as an answer to residence questions.'),
        ),
    ]
