# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0065_auto_20180119_0203'),
        ('pcari', '0063_auto_20180118_1104'),
    ]

    operations = [
    ]
