# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-02 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0068_merge_20180201_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitativequestion',
            name='input_type',
            field=models.CharField(choices=[('range', 'Slider'), ('number', 'Numeric text'), ('buttons', 'Buttons')], default='range', help_text='What user interface element should be used.', max_length=16),
        ),
    ]
