# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-02 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0066_merge_20180125_0718'),
        ('pcari', '0068_merge_20180201_1217'),
    ]

    operations = [
    ]
